### ISSUE TITLE
Chapter 12 Deployments typo for template annotations

### ISSUE THREAD

**Issue by michaelsrichter** [kubernetes-up-and-running/kuard#13]
page 126 - template doesn't have an annotations object (that is what the example seems to be suggesting) - annotations need to be created inside the metadata object of template

**Comment by epequeno** [comment]
currently 
```
spec:
  ...
  template:
    annotations:
      kubernetes.io/change-cause: "Update nginx to 1.9.10"
...
```
should be
```
spec:
  ...
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Update nginx to 1.9.10"
...
```
